version: '3'

services:
    # postgres:
    #     image: postgres:14-alpine
    #     ports:
    #     - "5428:5432"
    #     volumes:
    #     - ~/apps/postgres:/var/lib/postgresql/data
    #     environment:
    #         POSTGRES_PASSWORD: "12345"
    #         POSTGRES_USER: "postgres"
    #         POSTGRES_DB: "postgres"
    #     networks:
    #     - minha_rede

    cv_scanner:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: cv_scanner
        ports:
            - "8080:8080"
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            DB_HOST: postgres
            DB_NAME: postgres
            DB_USER: postgres
            DB_PORT: 5432
            DB_PASS: "12345"
        tty: true
        # depends_on:
        # - postgres
        # restart: never
        networks:
        - minha_rede


networks:
  minha_rede:
    driver: bridge